---
# tasks file for PeterMosmans.webgoat
- name: Install required packages
  apt:
    name: "{{ item }}"
    state: present
    install_recommends: false
  with_items:
    - default-jre-headless

- name: Add WebGoat user
  user:
    name: "{{ webgoat_user }}"
    state: present
  tags:
    - usermanagement

- name: Add WebGoat group
  group:
    name: "{{ webgoat_group }}"
    state: present
  tags:
    - usermanagement

- name: Prepare location for WebGoat
  file:
    path: "{{ webgoat_base }}"
    state: directory
    group: "{{ webgoat_group }}"
    mode: "0775"

- name: Download the standalone executable JAR file
  get_url:
    url: "{{ webgoat_url }}"
    dest: "{{ webgoat_base }}/webgoat.jar"
    group: "{{ webgoat_group }}"
    owner: "{{ webgoat_user }}"
    mode: "0755"

- name: Deploy templates to start WebGoat as a service
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  with_items:
    - src: webgoat.service.j2
      dest: /etc/systemd/system/webgoat.service
      mode: "0644"
    - src: webgoat.j2
      dest: /etc/init.d/webgoat
      mode: "0755"

- name: Enable webgoat service
  systemd:
    state: started
    name: webgoat
    enabled: yes
    daemon_reload: yes
